name: CI WORKFLOW

on:
  push:
    branches:
      - master
      - features/*
      - task/*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache vendor folder
        uses: actions/cache@v3
        with:
          path: /vendor
          key: ${{ github.sha }}
      - name: Install dependencies via composer
        run: composer install
  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Retrieve cached vendor folder
        uses: actions/cache@v3
        with:
          path: /vendor
          key: ${{ github.sha }}
      - name: Test > Unit
        run: vendor/bin/phpunit --testsuite Unit
